FROM ruby:3.4.1

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# apt-keyが非推奨のため、keyringsを使用する方法に変更
RUN apt-get update -qq \
&& apt-get install -y --no-install-recommends ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/yarn.gpg \
&& echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
&& apt-get update -qq \
&& apt-get install -y --no-install-recommends build-essential libpq-dev nodejs yarn vim \
# 不要なキャッシュを削除
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir /myapp
WORKDIR /myapp

# 依存ファイルだけ先にコピーしてインストール
COPY package.json yarn.lock ./
RUN yarn install

# アプリ全体をコピー
COPY . /myapp
RUN gem install bundler
RUN yarn install && ls -la node_modules/.bin
